// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "amazon-charts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "amazon-charts",
    "method": "GET",
    "paginatable": true,
    "path": "/amazon/charts",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "best_sellers",
          "new_releases",
          "most_wished_for"
        ],
        "in": "query",
        "name": "chart",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "department",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "node",
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "amazon-charts-categories": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "amazon-charts-categories",
    "method": "GET",
    "path": "/amazon/charts/categories",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "best_sellers",
          "new_releases",
          "most_wished_for"
        ],
        "in": "query",
        "name": "chart",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "department",
        "type": "string"
      },
      {
        "in": "query",
        "name": "node",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "amazon-product": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "amazon-product",
    "method": "GET",
    "path": "/amazon/product/{asin}",
    "pathParams": [
      "asin"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "en_US"
        ],
        "in": "query",
        "name": "language",
        "type": "string"
      },
      {
        "enum": [
          "USD"
        ],
        "in": "query",
        "name": "currency",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "amazon-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "amazon-search",
    "method": "GET",
    "paginatable": true,
    "path": "/amazon/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "k",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "s",
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "amazon-suggest": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "amazon-suggest",
    "method": "GET",
    "path": "/amazon/suggest/{keyword}",
    "pathParams": [
      "keyword"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "amazon": {
    "charts": "amazon-charts",
    "chartsCategories": "amazon-charts-categories",
    "product": "amazon-product",
    "search": "amazon-search",
    "suggest": "amazon-suggest"
  }
};

export const operationCount = 5;

export const OperationIds = Object.freeze({
  "AmazonCharts": "amazon-charts",
  "AmazonChartsCategories": "amazon-charts-categories",
  "AmazonProduct": "amazon-product",
  "AmazonSearch": "amazon-search",
  "AmazonSuggest": "amazon-suggest"
});
