// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelAmazonSuggestResponseDoc {
  "code"?: number;
  "data"?: Array<string>;
  "msg"?: string;
}

export interface ModelAmazonSearchResponseDoc {
  "code"?: number;
  "data"?: Array<ModelAmazonSearchResponseItem>;
  "msg"?: string;
}

export interface ModelAmazonSearchResponseItem {
  "asin"?: string;
  "image"?: string;
  "is_free_delivery"?: boolean;
  "is_sponsored"?: boolean;
  "link"?: string;
  "list_price"?: number;
  "more_choice"?: string;
  "number_of_bought_in_last_month"?: number;
  "price"?: number;
  "rating"?: number;
  "review_count"?: number;
  "title"?: string;
}

export interface ModelAmazonProductResponseDoc {
  "code"?: number;
  "data"?: ModelAmazonProduct;
  "msg"?: string;
}

export interface ModelAmazonProduct {
  "about"?: string;
  "asin"?: string;
  "availability"?: boolean;
  "brand_link"?: string;
  "brand_name"?: string;
  "customers_say"?: string;
  "description"?: string;
  "images"?: Array<string>;
  "is_free_delivery"?: boolean;
  "is_free_return"?: boolean;
  "link"?: string;
  "low_confidence"?: boolean;
  "number_of_bought_in_last_month"?: number;
  "overview"?: Record<string, string>;
  "price"?: number;
  "rating"?: number;
  "rating_hist"?: Record<string, number>;
  "review_count"?: number;
  "review_images"?: Array<ModelAmazonReviewImage>;
  "review_insights"?: Array<ModelAmazonReviewInsight>;
  "reviews"?: Array<ModelAmazonReview>;
  "seller_link"?: string;
  "seller_name"?: string;
  "title"?: string;
}

export interface ModelAmazonReview {
  "content"?: string;
  "country"?: string;
  "helpful_count"?: number;
  "link"?: string;
  "rating"?: number;
  "review_date"?: string;
  "title"?: string;
  "user_link"?: string;
  "user_name"?: string;
  "verified_purchase"?: boolean;
}

export interface ModelAmazonReviewInsight {
  "label"?: string;
  "mention_percent"?: number;
  "mentions"?: number;
  "sentiment"?: string;
  "summary"?: string;
}

export interface ModelAmazonReviewImage {
  "review_id"?: string;
  "thumbnail"?: string;
  "url"?: string;
}

export interface ModelAmazonChartCategoriesResponseDoc {
  "code"?: number;
  "data"?: ModelAmazonChartCategoriesResponse;
  "msg"?: string;
}

export interface ModelAmazonChartCategoriesResponse {
  "categories"?: Array<ModelAmazonChartCategory>;
  "category"?: ModelAmazonChartCategory;
  "chart"?: string;
  "department"?: string;
  "node"?: string;
}

export interface ModelAmazonChartCategory {
  "department"?: string;
  "link"?: string;
  "name"?: string;
  "node"?: string;
}

export interface ModelAmazonChartsResponseDoc {
  "code"?: number;
  "data"?: ModelAmazonChartResponse;
  "msg"?: string;
}

export interface ModelAmazonChartResponse {
  "category_name"?: string;
  "chart"?: string;
  "department"?: string;
  "has_next_page"?: boolean;
  "items"?: Array<ModelAmazonChartItem>;
  "node"?: string;
  "page"?: number;
  "source_url"?: string;
}

export interface ModelAmazonChartItem {
  "asin"?: string;
  "image"?: string;
  "link"?: string;
  "price"?: number;
  "rank"?: number;
  "rating"?: number;
  "review_count"?: number;
  "title"?: string;
}

export type AmazonChartsResponse = CrawloraResponse<ModelAmazonChartsResponseDoc>;
export interface AmazonChartsParams {
  "chart": "best_sellers" | "new_releases" | "most_wished_for";
  "department": string;
  "node"?: string;
  "page"?: number;
}

export type AmazonChartsCategoriesResponse = CrawloraResponse<ModelAmazonChartCategoriesResponseDoc>;
export interface AmazonChartsCategoriesParams {
  "chart": "best_sellers" | "new_releases" | "most_wished_for";
  "department"?: string;
  "node"?: string;
}

export type AmazonProductResponse = CrawloraResponse<ModelAmazonProductResponseDoc>;
export interface AmazonProductParams {
  "asin": string;
  "language"?: "en_US";
  "currency"?: "USD";
}

export type AmazonSearchResponse = CrawloraResponse<ModelAmazonSearchResponseDoc>;
export interface AmazonSearchParams {
  "k": string;
  "s"?: string;
  "page"?: number;
}

export type AmazonSuggestResponse = CrawloraResponse<ModelAmazonSuggestResponseDoc>;
export interface AmazonSuggestParams {
  "keyword": string;
}

export interface AmazonService {
  charts<T = AmazonChartsResponse>(params: AmazonChartsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  chartsCategories<T = AmazonChartsCategoriesResponse>(params: AmazonChartsCategoriesParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  product<T = AmazonProductResponse>(params: AmazonProductParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = AmazonSearchResponse>(params: AmazonSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  suggest<T = AmazonSuggestResponse>(params: AmazonSuggestParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  amazon: AmazonService;
}

export interface OperationParamsMap {
  "amazon-charts": AmazonChartsParams;
  "amazon-charts-categories": AmazonChartsCategoriesParams;
  "amazon-product": AmazonProductParams;
  "amazon-search": AmazonSearchParams;
  "amazon-suggest": AmazonSuggestParams;
}

export interface OperationResponseMap {
  "amazon-charts": AmazonChartsResponse;
  "amazon-charts-categories": AmazonChartsCategoriesResponse;
  "amazon-product": AmazonProductResponse;
  "amazon-search": AmazonSearchResponse;
  "amazon-suggest": AmazonSuggestResponse;
}

export interface OperationRequiredParamsMap {
  "amazon-charts": true;
  "amazon-charts-categories": true;
  "amazon-product": true;
  "amazon-search": true;
  "amazon-suggest": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "amazon-charts"
  | "amazon-charts-categories"
  | "amazon-product"
  | "amazon-search"
  | "amazon-suggest";

export declare const OperationIds: Readonly<{
  AmazonCharts: "amazon-charts";
  AmazonChartsCategories: "amazon-charts-categories";
  AmazonProduct: "amazon-product";
  AmazonSearch: "amazon-search";
  AmazonSuggest: "amazon-suggest";
}>;
