// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package amazon

import (
	"context"
	"sort"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"amazon-charts":            operationDefinition{Method: "GET", Path: "/amazon/charts", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "chart", In: "query", Type: "string", Required: true, Enum: []string{"best_sellers", "new_releases", "most_wished_for"}}, parameterDefinition{Name: "department", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "node", In: "query", Type: "string"}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"amazon-charts-categories": operationDefinition{Method: "GET", Path: "/amazon/charts/categories", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "chart", In: "query", Type: "string", Required: true, Enum: []string{"best_sellers", "new_releases", "most_wished_for"}}, parameterDefinition{Name: "department", In: "query", Type: "string"}, parameterDefinition{Name: "node", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"amazon-product":           operationDefinition{Method: "GET", Path: "/amazon/product/{asin}", PathParams: []string{"asin"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "language", In: "query", Type: "string", Enum: []string{"en_US"}}, parameterDefinition{Name: "currency", In: "query", Type: "string", Enum: []string{"USD"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"amazon-search":            operationDefinition{Method: "GET", Path: "/amazon/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "k", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "s", In: "query", Type: "string"}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"amazon-suggest":           operationDefinition{Method: "GET", Path: "/amazon/suggest/{keyword}", PathParams: []string{"keyword"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 5

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Charts calls the amazon-charts operation.
func (c *Client) Charts(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "amazon-charts", params)
}

// ChartsCategories calls the amazon-charts-categories operation.
func (c *Client) ChartsCategories(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "amazon-charts-categories", params)
}

// Product calls the amazon-product operation.
func (c *Client) Product(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "amazon-product", params)
}

// Search calls the amazon-search operation.
func (c *Client) Search(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "amazon-search", params)
}

// Suggest calls the amazon-suggest operation.
func (c *Client) Suggest(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "amazon-suggest", params)
}
